import type { PancakeSkin } from './skinEngine';

export interface ShopSkin {
  id: string;
  name: string;
  blurb: string;
  price: number;
  skin: PancakeSkin;
  /**
   * Limited-edition skin earned from a seasonal event — never for sale.
   * Hidden from the shop catalog when not owned (so missed-out players
   * don't see what they could have had). Shown with a "Limited Edition"
   * badge when owned, and equippable like any other skin.
   */
  limitedEdition?: boolean;
}

// Roster of buyable pancake skins. Sorted ascending by price so the shop
// scrolls cheap → expensive. "Default Stack" (null skin) is free and not
// in this list. IDs are STABLE — never rename, players' ownership is keyed
// on them.
export const SHOP_SKINS: ShopSkin[] = [
  {
    id: 'buttery-classic',
    name: 'Buttery Classic',
    blurb: 'A perfect golden stack with a pat of butter on top.',
    price: 250,
    skin: { name: 'Buttery Classic', baseColor: '#F0C85C', accentColor: '#D4A044', highlightColor: '#FFE082', topping: { type: 'butter' }, pattern: 'spots', patternColor: '#E8B84C' },
  },
  {
    id: 'cinnamon-roll',
    name: 'Cinnamon Roll',
    blurb: 'A warm brown swirl that smells like Sunday morning.',
    price: 500,
    skin: { name: 'Cinnamon Roll', baseColor: '#A1683A', accentColor: '#6B4226', highlightColor: '#C8915A', topping: { type: 'syrup', color: '#FFFFFF' }, pattern: 'swirl', patternColor: '#4B2A1C' },
  },
  {
    id: 'sour-cherry',
    name: 'Sour Cherry',
    blurb: 'Pucker up — tangy red cherries on a pale pancake.',
    price: 750,
    skin: { name: 'Sour Cherry', baseColor: '#FFEBEE', accentColor: '#EF9A9A', highlightColor: '#FFF5F5', topping: { type: 'berries', color: '#B71C1C' }, pattern: 'spots', patternColor: '#E57373' },
  },
  {
    id: 'banana-bread',
    name: 'Banana Bread',
    blurb: 'Soft, dense, and dotted with nutty brown specks.',
    price: 900,
    skin: { name: 'Banana Bread', baseColor: '#E6C68A', accentColor: '#8B5A2B', highlightColor: '#FFF0BE', topping: { type: 'none' }, pattern: 'spots', patternColor: '#6B4226' },
  },
  {
    id: 'graham-cracker',
    name: 'Graham Cracker',
    blurb: 'Toasty, sandy edges with that honey-cookie warmth.',
    price: 1_200,
    skin: { name: 'Graham Cracker', baseColor: '#C9925E', accentColor: '#8B5A2B', highlightColor: '#E5BC8A', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#6B4226' },
  },
  {
    id: 'powdered-sugar',
    name: 'Powdered Sugar',
    blurb: 'Dusted in white snow, sweet without trying too hard.',
    price: 2_000,
    skin: { name: 'Powdered Sugar', baseColor: '#FFE082', accentColor: '#FBC02D', highlightColor: '#FFF59D', topping: { type: 'sprinkles' }, pattern: 'spots', patternColor: '#FFFFFF' },
  },
  {
    id: 'french-toast',
    name: 'French Toast',
    blurb: 'Egg-washed and griddled to a deep custardy gold.',
    price: 3_500,
    skin: { name: 'French Toast', baseColor: '#D4974C', accentColor: '#8B5A2B', highlightColor: '#F0BB7A', topping: { type: 'syrup', color: '#FFFFFF' }, pattern: 'swirl', patternColor: '#A06A30' },
  },
  {
    id: 'maple-drizzle',
    name: 'Maple Drizzle',
    blurb: 'Deep amber syrup pouring over a toasty brown pancake.',
    price: 5_000,
    skin: { name: 'Maple Drizzle', baseColor: '#B87333', accentColor: '#8B5A2B', highlightColor: '#DDA15E', topping: { type: 'syrup', color: '#5C2E0F' }, pattern: 'swirl', patternColor: '#6B3410' },
  },
  {
    id: 'banana-foster',
    name: 'Banana Foster',
    blurb: 'Caramelized banana and a flicker of rum-fire glow.',
    price: 7_500,
    skin: { name: 'Banana Foster', baseColor: '#FFE082', accentColor: '#F9A825', highlightColor: '#FFEE58', topping: { type: 'syrup', color: '#5D4037' }, pattern: 'swirl', patternColor: '#8D6E63', glow: '#FFB300' },
  },
  {
    id: 'crepe-suzette',
    name: 'Crêpe Suzette',
    blurb: 'Thin, elegant, and lit up with a touch of orange flambé.',
    price: 9_000,
    skin: { name: 'Crêpe Suzette', baseColor: '#FFB74D', accentColor: '#E65100', highlightColor: '#FFCC80', topping: { type: 'syrup', color: '#D84315' }, pattern: 'swirl', patternColor: '#FB8C00', glow: '#FF7043' },
  },
  {
    id: 'apple-pie',
    name: 'Apple Pie',
    blurb: 'Cinnamon-spiced and pie-crust gold. Tastes like home.',
    price: 15_000,
    skin: { name: 'Apple Pie', baseColor: '#E6BB7A', accentColor: '#8B5A2B', highlightColor: '#F5D294', topping: { type: 'chocolate', color: '#6B4226' }, pattern: 'stripes', patternColor: '#A06A30' },
  },
  {
    id: 'orange-zest',
    name: 'Orange Zest',
    blurb: 'A bright citrus burst, dotted with peel and pith.',
    price: 25_000,
    skin: { name: 'Orange Zest', baseColor: '#FB8C00', accentColor: '#E65100', highlightColor: '#FFCC80', topping: { type: 'sprinkles' }, pattern: 'spots', patternColor: '#FFF59D' },
  },
  {
    id: 'lemon-meringue',
    name: 'Lemon Meringue',
    blurb: 'Tart lemon under fluffy snow-white peaks.',
    price: 40_000,
    skin: { name: 'Lemon Meringue', baseColor: '#FFF176', accentColor: '#FBC02D', highlightColor: '#FFF59D', topping: { type: 'butter' }, pattern: 'swirl', patternColor: '#FFFFFF' },
  },
  {
    id: 'peach-cobbler',
    name: 'Peach Cobbler',
    blurb: 'Soft peach fuzz folded under sugary biscuit waves.',
    price: 60_000,
    skin: { name: 'Peach Cobbler', baseColor: '#FFAB91', accentColor: '#D84315', highlightColor: '#FFCCBC', topping: { type: 'chocolate', color: '#6B4226' }, pattern: 'swirl', patternColor: '#FF7043' },
  },
  {
    id: 'matcha-latte',
    name: 'Matcha Latte',
    blurb: 'Earthy green tea powder swirled into creamy foam.',
    price: 75_000,
    skin: { name: 'Matcha Latte', baseColor: '#9CCC65', accentColor: '#558B2F', highlightColor: '#C5E1A5', topping: { type: 'syrup', color: '#FFFFFF' }, pattern: 'swirl', patternColor: '#7CB342' },
  },
  {
    id: 'red-velvet',
    name: 'Red Velvet',
    blurb: 'Deep crimson cake with a frosted swirl on top.',
    price: 90_000,
    skin: { name: 'Red Velvet', baseColor: '#C62828', accentColor: '#7F0000', highlightColor: '#EF5350', topping: { type: 'syrup', color: '#FFFFFF' }, pattern: 'swirl', patternColor: '#B71C1C' },
  },
  {
    id: 'blueberry-burst',
    name: 'Blueberry Burst',
    blurb: 'Plump berries scattered across a fluffy golden disc.',
    price: 100_000,
    skin: { name: 'Blueberry Burst', baseColor: '#E8B84C', accentColor: '#C89532', highlightColor: '#F0C85C', topping: { type: 'berries', color: '#1976D2' }, pattern: 'spots', patternColor: '#1565C0' },
  },
  {
    id: 'cookies-cream',
    name: 'Cookies & Cream',
    blurb: 'Pale vanilla shocked with shards of midnight cocoa.',
    price: 200_000,
    skin: { name: 'Cookies & Cream', baseColor: '#ECEFF1', accentColor: '#90A4AE', highlightColor: '#FFFFFF', topping: { type: 'chocolate', color: '#212121' }, pattern: 'spots', patternColor: '#212121' },
  },
  {
    id: 'salted-caramel',
    name: 'Salted Caramel',
    blurb: 'Buttery caramel kissed with crystalline sea salt.',
    price: 350_000,
    skin: { name: 'Salted Caramel', baseColor: '#D4A044', accentColor: '#8B5A2B', highlightColor: '#F0BB7A', topping: { type: 'sprinkles' }, pattern: 'swirl', patternColor: '#FFFFFF' },
  },
  {
    id: 'pumpkin-spice',
    name: 'Pumpkin Spice',
    blurb: 'Autumn in a stack: cinnamon, nutmeg, and a slow glow.',
    price: 500_000,
    skin: { name: 'Pumpkin Spice', baseColor: '#FB8C00', accentColor: '#BF360C', highlightColor: '#FFB74D', topping: { type: 'chocolate', color: '#3E2723' }, pattern: 'stripes', patternColor: '#E65100', glow: '#FF7043' },
  },
  {
    id: 'tiramisu',
    name: 'Tiramisu',
    blurb: 'Coffee-soaked layers dusted with bittersweet cocoa.',
    price: 750_000,
    skin: { name: 'Tiramisu', baseColor: '#D7B48A', accentColor: '#4E342E', highlightColor: '#EDD2A8', topping: { type: 'sprinkles' }, pattern: 'stripes', patternColor: '#3E2723' },
  },
  {
    id: 'mocha-latte',
    name: 'Mocha Latte',
    blurb: 'Espresso swirled with chocolate and steamed milk art.',
    price: 900_000,
    skin: { name: 'Mocha Latte', baseColor: '#6D4C41', accentColor: '#3E2723', highlightColor: '#A1887F', topping: { type: 'syrup', color: '#FFFFFF' }, pattern: 'swirl', patternColor: '#FFFFFF' },
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    blurb: 'Sticky-sweet pink, big enough to blow a bubble in.',
    price: 1_500_000,
    skin: { name: 'Bubblegum', baseColor: '#F8BBD0', accentColor: '#EC407A', highlightColor: '#FCE4EC', topping: { type: 'sprinkles' }, pattern: 'spots', patternColor: '#FF4081' },
  },
  {
    id: 'chocolate-chip',
    name: 'Chocolate Chip',
    blurb: 'Rich cocoa drizzle and chips on a buttery brown base.',
    price: 2_500_000,
    skin: { name: 'Chocolate Chip', baseColor: '#D7A86E', accentColor: '#8B5A2B', highlightColor: '#E6C68A', topping: { type: 'chocolate', color: '#3E2723' }, pattern: 'spots', patternColor: '#5D4037' },
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    blurb: 'Spun-sugar pink and blue, fluffy enough to float.',
    price: 3_000_000,
    skin: { name: 'Cotton Candy', baseColor: '#F8BBD0', accentColor: '#81D4FA', highlightColor: '#FCE4EC', topping: { type: 'sprinkles' }, pattern: 'swirl', patternColor: '#4FC3F7' },
  },
  {
    id: 'gingerbread',
    name: 'Gingerbread',
    blurb: 'Holiday spice with white icing piped in cheerful loops.',
    price: 5_000_000,
    skin: { name: 'Gingerbread', baseColor: '#A1683A', accentColor: '#5D4037', highlightColor: '#C8915A', topping: { type: 'syrup', color: '#FFFFFF' }, pattern: 'swirl', patternColor: '#FFFFFF' },
  },
  {
    id: 'candy-cane',
    name: 'Candy Cane',
    blurb: 'Peppermint stripes that taste like cold December air.',
    price: 7_500_000,
    skin: { name: 'Candy Cane', baseColor: '#FFFFFF', accentColor: '#C62828', highlightColor: '#FFEBEE', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#D32F2F' },
  },
  {
    id: 'pina-colada',
    name: 'Piña Colada',
    blurb: 'Tropical creamy coconut with pineapple sunshine.',
    price: 15_000_000,
    skin: { name: 'Piña Colada', baseColor: '#FFF59D', accentColor: '#FBC02D', highlightColor: '#FFFDE7', topping: { type: 'emoji', emoji: '🍍' }, pattern: 'swirl', patternColor: '#FFFFFF' },
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    blurb: 'Crisp red rind with seedy black flecks. Cold and juicy.',
    price: 30_000_000,
    skin: { name: 'Watermelon', baseColor: '#E53935', accentColor: '#388E3C', highlightColor: '#EF9A9A', topping: { type: 'sprinkles' }, pattern: 'spots', patternColor: '#212121' },
  },
  {
    id: 'creme-brulee',
    name: 'Crème Brûlée',
    blurb: 'Glassy torched sugar over silky vanilla custard.',
    price: 50_000_000,
    skin: { name: 'Crème Brûlée', baseColor: '#FFE082', accentColor: '#FB8C00', highlightColor: '#FFF59D', topping: { type: 'syrup', color: '#BF360C' }, pattern: 'plain', glow: '#FFAB00' },
  },
  {
    id: 'smores',
    name: "S'mores",
    blurb: 'Toasted marshmallow on chocolate, around a fire glow.',
    price: 75_000_000,
    skin: { name: "S'mores", baseColor: '#A1683A', accentColor: '#3E2723', highlightColor: '#FFFFFF', topping: { type: 'chocolate', color: '#3E2723' }, pattern: 'swirl', patternColor: '#FFFFFF', glow: '#FF6F00' },
  },
  {
    id: 'strawberry-sweet',
    name: 'Strawberry Sweet',
    blurb: 'Pink and proud, dressed up with red berries and stars.',
    price: 100_000_000,
    skin: { name: 'Strawberry Sweet', baseColor: '#FFAB91', accentColor: '#FF7043', highlightColor: '#FFCCBC', topping: { type: 'berries', color: '#C62828' }, pattern: 'stars', patternColor: '#D81B60' },
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    blurb: 'Pale pink petals drifting on a still spring breeze.',
    price: 200_000_000,
    skin: { name: 'Cherry Blossom', baseColor: '#FCE4EC', accentColor: '#F8BBD0', highlightColor: '#FFFFFF', topping: { type: 'emoji', emoji: '🌸' }, pattern: 'stars', patternColor: '#F48FB1' },
  },
  {
    id: 'autumn-leaves',
    name: 'Autumn Leaves',
    blurb: 'Rust, amber, and burnt orange tumbling on a chill wind.',
    price: 400_000_000,
    skin: { name: 'Autumn Leaves', baseColor: '#D84315', accentColor: '#3E2723', highlightColor: '#FF7043', topping: { type: 'emoji', emoji: '🍂' }, pattern: 'swirl', patternColor: '#BF360C' },
  },
  {
    id: 'winter-frost',
    name: 'Winter Frost',
    blurb: 'A pale blue chill with crystallized flakes catching light.',
    price: 700_000_000,
    skin: { name: 'Winter Frost', baseColor: '#E1F5FE', accentColor: '#4FC3F7', highlightColor: '#FFFFFF', topping: { type: 'sprinkles' }, pattern: 'stars', patternColor: '#81D4FA', glow: '#B3E5FC' },
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    blurb: 'Ribbons of green and violet rippling overhead.',
    price: 2_000_000_000,
    skin: { name: 'Aurora Borealis', baseColor: '#1B5E20', accentColor: '#6A1B9A', highlightColor: '#81C784', topping: { type: 'none' }, pattern: 'swirl', patternColor: '#E1BEE7', glow: '#69F0AE' },
  },
  {
    id: 'thunderstorm',
    name: 'Thunderstorm',
    blurb: 'Slate clouds cracked open by a single bolt of white.',
    price: 4_500_000_000,
    skin: { name: 'Thunderstorm', baseColor: '#455A64', accentColor: '#263238', highlightColor: '#90A4AE', topping: { type: 'emoji', emoji: '⚡' }, pattern: 'stripes', patternColor: '#ECEFF1', glow: '#FFEB3B' },
  },
  {
    id: 'birthday-funfetti',
    name: 'Birthday Funfetti',
    blurb: 'A pastel party stack with every color of sprinkle.',
    price: 5_000_000_000,
    skin: { name: 'Birthday Funfetti', baseColor: '#FFCDD2', accentColor: '#F8BBD0', highlightColor: '#FCE4EC', topping: { type: 'sprinkles' }, pattern: 'stars', patternColor: '#EC407A' },
  },
  {
    id: 'ocean-wave',
    name: 'Ocean Wave',
    blurb: 'A deep teal swell capped with white foam crashing in.',
    price: 7_000_000_000,
    skin: { name: 'Ocean Wave', baseColor: '#0277BD', accentColor: '#01579B', highlightColor: '#4FC3F7', topping: { type: 'syrup', color: '#FFFFFF' }, pattern: 'swirl', patternColor: '#B3E5FC' },
  },
  {
    id: 'lava-flow',
    name: 'Lava Flow',
    blurb: 'Molten orange cracking through cooled volcanic black.',
    price: 15_000_000_000,
    skin: { name: 'Lava Flow', baseColor: '#212121', accentColor: '#000000', highlightColor: '#BF360C', topping: { type: 'chocolate', color: '#FF6F00' }, pattern: 'swirl', patternColor: '#FF3D00', glow: '#FF6F00' },
  },
  {
    id: 'desert-mirage',
    name: 'Desert Mirage',
    blurb: 'Sandy gold rippling like heat over a hidden oasis.',
    price: 30_000_000_000,
    skin: { name: 'Desert Mirage', baseColor: '#FFE0B2', accentColor: '#FB8C00', highlightColor: '#FFF3E0', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#F57C00' },
  },
  {
    id: 'glacier-ice',
    name: 'Glacier Ice',
    blurb: 'Ancient blue ice, pressure-locked and impossibly clear.',
    price: 60_000_000_000,
    skin: { name: 'Glacier Ice', baseColor: '#B3E5FC', accentColor: '#0277BD', highlightColor: '#E1F5FE', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#4FC3F7', glow: '#81D4FA' },
  },
  {
    id: 'tiger-stripe',
    name: 'Tiger Stripe',
    blurb: 'Fierce orange streaked with bold black bands.',
    price: 125_000_000_000,
    skin: { name: 'Tiger Stripe', baseColor: '#FB8C00', accentColor: '#212121', highlightColor: '#FFB74D', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#212121' },
  },
  {
    id: 'zebra-print',
    name: 'Zebra Print',
    blurb: 'High-contrast monochrome stripes you can spot a mile away.',
    price: 175_000_000_000,
    skin: { name: 'Zebra Print', baseColor: '#FFFFFF', accentColor: '#000000', highlightColor: '#FAFAFA', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#212121' },
  },
  {
    id: 'mint-chocolate',
    name: 'Mint Chocolate',
    blurb: 'Cool mint disc with a melty cocoa swirl on top.',
    price: 250_000_000_000,
    skin: { name: 'Mint Chocolate', baseColor: '#A5D6A7', accentColor: '#388E3C', highlightColor: '#C8E6C9', topping: { type: 'chocolate', color: '#2E1A0A' }, pattern: 'spots', patternColor: '#3E2723' },
  },
  {
    id: 'leopard-spot',
    name: 'Leopard Spot',
    blurb: 'Tawny gold dappled with dark rosette spots.',
    price: 350_000_000_000,
    skin: { name: 'Leopard Spot', baseColor: '#D4A044', accentColor: '#5D4037', highlightColor: '#FFCA28', topping: { type: 'none' }, pattern: 'spots', patternColor: '#3E2723' },
  },
  {
    id: 'cow-print',
    name: 'Cow Print',
    blurb: 'Splotchy black-and-white. Farm-fresh aesthetic.',
    price: 600_000_000_000,
    skin: { name: 'Cow Print', baseColor: '#FFFFFF', accentColor: '#FAFAFA', highlightColor: '#FFFFFF', topping: { type: 'none' }, pattern: 'spots', patternColor: '#212121' },
  },
  {
    id: 'unicorn-magic',
    name: 'Unicorn Magic',
    blurb: 'Pearlescent pastels with a mane of pure rainbow.',
    price: 1.5e12,
    skin: { name: 'Unicorn Magic', baseColor: '#F8BBD0', accentColor: '#CE93D8', highlightColor: '#FFFFFF', topping: { type: 'emoji', emoji: '🦄' }, pattern: 'stars', patternColor: '#E1BEE7', glow: '#F48FB1' },
  },
  {
    id: 'phoenix-flame',
    name: 'Phoenix Flame',
    blurb: 'Reborn from gold and crimson fire over and over again.',
    price: 8e12,
    skin: { name: 'Phoenix Flame', baseColor: '#FF6F00', accentColor: '#BF360C', highlightColor: '#FFEB3B', topping: { type: 'emoji', emoji: '🔥' }, pattern: 'swirl', patternColor: '#FFD600', glow: '#FF3D00' },
  },
  {
    id: 'dragon-scale',
    name: 'Dragon Scale',
    blurb: 'Iridescent emerald plates that ripple as you move.',
    price: 15e12,
    skin: { name: 'Dragon Scale', baseColor: '#1B5E20', accentColor: '#004D40', highlightColor: '#66BB6A', topping: { type: 'none' }, pattern: 'spots', patternColor: '#00C853', glow: '#69F0AE' },
  },
  {
    id: 'cosmic-stardust',
    name: 'Cosmic Stardust',
    blurb: 'A nebula condensed into pancake form, glowing softly.',
    price: 25e12,
    skin: { name: 'Cosmic Stardust', baseColor: '#6A1B9A', accentColor: '#4527A0', highlightColor: '#9C27B0', topping: { type: 'emoji', emoji: '✨' }, pattern: 'stars', patternColor: '#E1BEE7', glow: '#BA68C8' },
  },
  {
    id: 'mermaid-tail',
    name: 'Mermaid Tail',
    blurb: 'Shimmering scales of seafoam, teal, and pearl.',
    price: 50e12,
    skin: { name: 'Mermaid Tail', baseColor: '#26C6DA', accentColor: '#00695C', highlightColor: '#80DEEA', topping: { type: 'emoji', emoji: '🧜' }, pattern: 'spots', patternColor: '#00ACC1', glow: '#84FFFF' },
  },
  {
    id: 'wizard-robe',
    name: 'Wizard Robe',
    blurb: 'Deep midnight blue, dotted with constellations.',
    price: 90e12,
    skin: { name: 'Wizard Robe', baseColor: '#1A237E', accentColor: '#0D1B5C', highlightColor: '#3949AB', topping: { type: 'emoji', emoji: '🧙' }, pattern: 'stars', patternColor: '#FFEB3B' },
  },
  {
    id: 'witches-brew',
    name: "Witch's Brew",
    blurb: 'A bubbling green cauldron in pancake form. Lightly cursed.',
    price: 200e12,
    skin: { name: "Witch's Brew", baseColor: '#1B5E20', accentColor: '#0D2B11', highlightColor: '#66BB6A', topping: { type: 'emoji', emoji: '🧪' }, pattern: 'swirl', patternColor: '#7CB342', glow: '#76FF03' },
  },
  {
    id: 'haunted-house',
    name: 'Haunted House',
    blurb: 'Gloomy purples, creaky shadows, and a ghostly glow.',
    price: 500e12,
    skin: { name: 'Haunted House', baseColor: '#311B92', accentColor: '#000000', highlightColor: '#7E57C2', topping: { type: 'emoji', emoji: '👻' }, pattern: 'spots', patternColor: '#212121', glow: '#B388FF' },
  },
  {
    id: 'vampire-bite',
    name: 'Vampire Bite',
    blurb: 'Pale skin with two perfect drops of crimson.',
    price: 800e12,
    skin: { name: 'Vampire Bite', baseColor: '#FAFAFA', accentColor: '#B71C1C', highlightColor: '#FFFFFF', topping: { type: 'berries', color: '#7F0000' }, pattern: 'spots', patternColor: '#C62828' },
  },
  {
    id: 'rainbow-prism',
    name: 'Rainbow Prism',
    blurb: 'Light bends across this pancake like a syrup-soaked rainbow.',
    price: 1e15,
    skin: { name: 'Rainbow Prism', baseColor: '#00BCD4', accentColor: '#E91E63', highlightColor: '#FFEB3B', topping: { type: 'sprinkles' }, pattern: 'stripes', patternColor: '#FFFFFF', glow: '#00E5FF' },
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    blurb: 'Low-res square stack from the 8-bit era of breakfast.',
    price: 1.5e15,
    skin: { name: 'Pixel Art', baseColor: '#FFC107', accentColor: '#212121', highlightColor: '#FFEB3B', topping: { type: 'none' }, pattern: 'spots', patternColor: '#212121', text: 'PXL' },
  },
  {
    id: 'neon-lights',
    name: 'Neon Lights',
    blurb: 'Hot pink and electric cyan buzzing under a dark sky.',
    price: 5e15,
    skin: { name: 'Neon Lights', baseColor: '#212121', accentColor: '#FF0080', highlightColor: '#00E5FF', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#FF0080', glow: '#FF0080' },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    blurb: 'Black market chrome, rain-slick streets, lethal style.',
    price: 50e15,
    skin: { name: 'Cyberpunk', baseColor: '#0D0D0D', accentColor: '#FFEB3B', highlightColor: '#FF1744', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#FFEB3B', glow: '#FF1744', text: '404' },
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    blurb: 'Mall-pink, palm-tree teal, and a serif font that means nothing.',
    price: 500e15,
    skin: { name: 'Vaporwave', baseColor: '#FF80AB', accentColor: '#80DEEA', highlightColor: '#FFCDD2', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#26C6DA', glow: '#FF4081', text: 'VIBE' },
  },
  {
    id: 'holographic',
    name: 'Holographic',
    blurb: 'Catches the light in pink, blue, and impossible gold.',
    price: 1.5e18,
    skin: { name: 'Holographic', baseColor: '#E1BEE7', accentColor: '#80DEEA', highlightColor: '#FFF59D', topping: { type: 'sprinkles' }, pattern: 'swirl', patternColor: '#F48FB1', glow: '#B388FF' },
  },
  {
    id: 'chrome-plate',
    name: 'Chrome Plate',
    blurb: 'Polished mirror finish. You can see yourself in it.',
    price: 50e18,
    skin: { name: 'Chrome Plate', baseColor: '#CFD8DC', accentColor: '#37474F', highlightColor: '#FFFFFF', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#90A4AE', glow: '#ECEFF1' },
  },
  {
    id: 'carbon-fiber',
    name: 'Carbon Fiber',
    blurb: 'Woven into a lightweight, indestructible matte black.',
    price: 500e18,
    skin: { name: 'Carbon Fiber', baseColor: '#212121', accentColor: '#000000', highlightColor: '#424242', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#616161' },
  },
  {
    id: 'golden-eagle',
    name: 'Golden Eagle',
    blurb: 'Solid 24-karat. The pancake every chef whispers about.',
    price: 1e21,
    skin: { name: 'Golden Eagle', baseColor: '#FFD700', accentColor: '#B8860B', highlightColor: '#FFF59D', topping: { type: 'butter' }, pattern: 'stars', patternColor: '#FFB300', glow: '#FFD700' },
  },
  {
    id: 'opal-shimmer',
    name: 'Opal Shimmer',
    blurb: 'Milky white with deep flashes of every color trapped inside.',
    price: 5e21,
    skin: { name: 'Opal Shimmer', baseColor: '#F3E5F5', accentColor: '#80DEEA', highlightColor: '#FFFFFF', topping: { type: 'sprinkles' }, pattern: 'stars', patternColor: '#CE93D8', glow: '#B388FF' },
  },
  {
    id: 'amethyst-cluster',
    name: 'Amethyst Cluster',
    blurb: 'Sharp violet crystals grown together over a thousand years.',
    price: 50e21,
    skin: { name: 'Amethyst Cluster', baseColor: '#7E57C2', accentColor: '#4A148C', highlightColor: '#B39DDB', topping: { type: 'none' }, pattern: 'stars', patternColor: '#E1BEE7', glow: '#B388FF' },
  },
  {
    id: 'emerald-cave',
    name: 'Emerald Cave',
    blurb: 'Deep green stone radiating jungle-warm light.',
    price: 500e21,
    skin: { name: 'Emerald Cave', baseColor: '#1B5E20', accentColor: '#004D40', highlightColor: '#4CAF50', topping: { type: 'none' }, pattern: 'spots', patternColor: '#00C853', glow: '#69F0AE' },
  },
  {
    id: 'topaz-fire',
    name: 'Topaz Fire',
    blurb: 'Honey-amber crystal lit from within by trapped sun.',
    price: 1e25,
    skin: { name: 'Topaz Fire', baseColor: '#FFB300', accentColor: '#FF6F00', highlightColor: '#FFE082', topping: { type: 'none' }, pattern: 'stars', patternColor: '#FFD600', glow: '#FFD600' },
  },
  {
    id: 'sapphire-deep',
    name: 'Sapphire Deep',
    blurb: 'Royal blue with edges sharp enough to cut a memory.',
    price: 1e27,
    skin: { name: 'Sapphire Deep', baseColor: '#0D47A1', accentColor: '#01579B', highlightColor: '#42A5F5', topping: { type: 'none' }, pattern: 'stars', patternColor: '#82B1FF', glow: '#448AFF' },
  },
  {
    id: 'jade-zen',
    name: 'Jade Zen',
    blurb: 'Cool green stone polished smooth by a hundred years of hands.',
    price: 1e29,
    skin: { name: 'Jade Zen', baseColor: '#4DB6AC', accentColor: '#00695C', highlightColor: '#80CBC4', topping: { type: 'none' }, pattern: 'swirl', patternColor: '#26A69A' },
  },
  {
    id: 'plasma-storm',
    name: 'Plasma Storm',
    blurb: 'Magenta and electric blue lightning chasing itself.',
    price: 1e32,
    skin: { name: 'Plasma Storm', baseColor: '#E91E63', accentColor: '#311B92', highlightColor: '#F8BBD0', topping: { type: 'none' }, pattern: 'swirl', patternColor: '#7C4DFF', glow: '#FF4081' },
  },
  {
    id: 'solar-flare',
    name: 'Solar Flare',
    blurb: 'A coronal eruption mid-burst, blinding and warm.',
    price: 1e34,
    skin: { name: 'Solar Flare', baseColor: '#FFC107', accentColor: '#E65100', highlightColor: '#FFEB3B', topping: { type: 'emoji', emoji: '☀️' }, pattern: 'swirl', patternColor: '#FF6F00', glow: '#FFEB3B' },
  },
  {
    id: 'black-hole-edge',
    name: 'Black Hole Edge',
    blurb: 'Pure dark with a halo of light bent into a single ring.',
    price: 1e36,
    skin: { name: 'Black Hole Edge', baseColor: '#000000', accentColor: '#FFAB00', highlightColor: '#212121', topping: { type: 'none' }, pattern: 'swirl', patternColor: '#FFD600', glow: '#FF6F00' },
  },
  {
    id: 'asteroid-belt',
    name: 'Asteroid Belt',
    blurb: 'A field of cratered grey rocks tumbling forever.',
    price: 1e38,
    skin: { name: 'Asteroid Belt', baseColor: '#546E7A', accentColor: '#263238', highlightColor: '#90A4AE', topping: { type: 'sprinkles' }, pattern: 'spots', patternColor: '#263238' },
  },
  {
    id: 'diamond-dawn',
    name: 'Diamond Dawn',
    blurb: 'Frozen sunrise carved into a perfect crystal pancake.',
    price: 1e40,
    skin: { name: 'Diamond Dawn', baseColor: '#B3E5FC', accentColor: '#03A9F4', highlightColor: '#E1F5FE', topping: { type: 'emoji', emoji: '💎' }, pattern: 'stars', patternColor: '#FFFFFF', glow: '#4FC3F7' },
  },
  {
    id: 'andromeda-spiral',
    name: 'Andromeda Spiral',
    blurb: "Our nearest galactic neighbor, slowly drifting our way.",
    price: 1e42,
    skin: { name: 'Andromeda Spiral', baseColor: '#311B92', accentColor: '#FFE082', highlightColor: '#5C6BC0', topping: { type: 'none' }, pattern: 'swirl', patternColor: '#FFD54F', glow: '#FFAB00' },
  },
  {
    id: 'supernova-burst',
    name: 'Supernova Burst',
    blurb: 'A star ending itself in a flash of every color at once.',
    price: 1e44,
    skin: { name: 'Supernova Burst', baseColor: '#FF1744', accentColor: '#FFEB3B', highlightColor: '#FF80AB', topping: { type: 'emoji', emoji: '💥' }, pattern: 'stars', patternColor: '#FFFFFF', glow: '#FFEB3B' },
  },
  {
    id: 'quasar-pulse',
    name: 'Quasar Pulse',
    blurb: 'A galactic core, brighter than every star around it combined.',
    price: 1e46,
    skin: { name: 'Quasar Pulse', baseColor: '#0D47A1', accentColor: '#000000', highlightColor: '#82B1FF', topping: { type: 'none' }, pattern: 'stars', patternColor: '#E3F2FD', glow: '#00B0FF' },
  },
  {
    id: 'dark-matter',
    name: 'Dark Matter',
    blurb: 'You can’t see it. It’s definitely there. Mostly.',
    price: 1e48,
    skin: { name: 'Dark Matter', baseColor: '#0D0D0D', accentColor: '#212121', highlightColor: '#424242', topping: { type: 'none' }, pattern: 'plain', glow: '#7C4DFF' },
  },
  {
    id: 'time-warp',
    name: 'Time Warp',
    blurb: "Yesterday's pancake from tomorrow's stack. Or vice versa.",
    price: 1e55,
    skin: { name: 'Time Warp', baseColor: '#37474F', accentColor: '#FFD600', highlightColor: '#78909C', topping: { type: 'emoji', emoji: '⏳' }, pattern: 'swirl', patternColor: '#FFEB3B', glow: '#FFD600' },
  },
  {
    id: 'parallel-shift',
    name: 'Parallel Shift',
    blurb: 'Two universes layered on the same plate. Smells weird.',
    price: 1e65,
    skin: { name: 'Parallel Shift', baseColor: '#E91E63', accentColor: '#00BCD4', highlightColor: '#FFFFFF', topping: { type: 'none' }, pattern: 'stripes', patternColor: '#00ACC1', glow: '#FF4081' },
  },
  {
    id: 'event-horizon',
    name: 'Event Horizon',
    blurb: 'Past this point, nothing comes back. Including breakfast.',
    price: 1e75,
    skin: { name: 'Event Horizon', baseColor: '#000000', accentColor: '#FF6F00', highlightColor: '#212121', topping: { type: 'none' }, pattern: 'swirl', patternColor: '#FFAB00', glow: '#FFD600' },
  },
  {
    id: 'infinity-stack',
    name: 'Infinity Stack',
    blurb: 'The legend. A galaxy folded inside a pancake. Practically priceless.',
    price: 1e80,
    skin: { name: 'Infinity Stack', baseColor: '#1A237E', accentColor: '#311B92', highlightColor: '#5C6BC0', topping: { type: 'emoji', emoji: '🌌' }, pattern: 'stars', patternColor: '#FFEB3B', glow: '#00E5FF' },
  },
  {
    id: 'multiverse-mosaic',
    name: 'Multiverse Mosaic',
    blurb: 'Every possible pancake that ever was, stacked on one plate.',
    price: 1e85,
    skin: { name: 'Multiverse Mosaic', baseColor: '#4A148C', accentColor: '#E91E63', highlightColor: '#7C4DFF', topping: { type: 'sprinkles' }, pattern: 'stars', patternColor: '#FFD600', glow: '#FF4081' },
  },
  {
    id: 'pre-big-bang',
    name: 'Pre-Big-Bang',
    blurb: 'Compressed batter the size of a pinhead. About to go off.',
    price: 1e92,
    skin: { name: 'Pre-Big-Bang', baseColor: '#FFAB00', accentColor: '#000000', highlightColor: '#FFFFFF', topping: { type: 'emoji', emoji: '🌟' }, pattern: 'stars', patternColor: '#FFEB3B', glow: '#FFFFFF', text: 'T-1' },
  },
  {
    id: 'omega-stack',
    name: 'Omega Stack',
    blurb: 'The last pancake. After this, the simulation ends.',
    price: 1e98,
    skin: { name: 'Omega Stack', baseColor: '#000000', accentColor: '#FFFFFF', highlightColor: '#FFD700', topping: { type: 'emoji', emoji: 'Ω' }, pattern: 'stars', patternColor: '#FFFFFF', glow: '#FFD700', text: 'Ω' },
  },

  // ====================== LIMITED-EDITION HOLIDAY SKINS ======================
  // Never for sale. Only awarded by being present during the matching
  // seasonal event. Hidden from the shop catalog when not owned.
  {
    id: 'le-jack-o-lantern',
    name: 'Jack-o\'-Lantern',
    blurb: 'Carved-pumpkin orange with a flickering candlelight glow.',
    price: Infinity,
    limitedEdition: true,
    skin: { name: 'Jack-o\'-Lantern', baseColor: '#FF7518', accentColor: '#1A1A1A', highlightColor: '#FFB347', topping: { type: 'emoji', emoji: '🎃' }, pattern: 'spots', patternColor: '#1A1A1A', glow: '#FF7518' },
  },
  {
    id: 'le-frosty-gingerbread',
    name: 'Frosty Gingerbread',
    blurb: 'Gingerbread piped with white icing and a Christmas-tree topper.',
    price: Infinity,
    limitedEdition: true,
    skin: { name: 'Frosty Gingerbread', baseColor: '#A66533', accentColor: '#FFFFFF', highlightColor: '#D4915E', topping: { type: 'emoji', emoji: '🎄' }, pattern: 'swirl', patternColor: '#FFFFFF', glow: '#F0F8FF' },
  },
  {
    id: 'le-midnight-sparkle',
    name: 'Midnight Sparkle',
    blurb: 'A New Year sky cracking open with gold and silver fireworks.',
    price: Infinity,
    limitedEdition: true,
    skin: { name: 'Midnight Sparkle', baseColor: '#1A1A2E', accentColor: '#FFD700', highlightColor: '#4A4E69', topping: { type: 'emoji', emoji: '🎆' }, pattern: 'stars', patternColor: '#FFD700', glow: '#FFD700' },
  },
  {
    id: 'le-sweetheart',
    name: 'Sweetheart Box',
    blurb: 'Soft pink with a glittering Valentine\'s heart on top.',
    price: Infinity,
    limitedEdition: true,
    skin: { name: 'Sweetheart Box', baseColor: '#FFC0CB', accentColor: '#C71585', highlightColor: '#FFB6C1', topping: { type: 'emoji', emoji: '💖' }, pattern: 'spots', patternColor: '#FF1493', glow: '#FF69B4' },
  },
];

export function findShopSkinById(id: string): ShopSkin | undefined {
  return SHOP_SKINS.find(s => s.id === id);
}
